# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  sentry_enabled: false
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  omniauth:
    facebook:
      enabled: true
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: true
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  geocoder:
    here_api_key: <%= ENV["HERE_API_KEY"] %>
  census_url: <%= ENV["CENSUS_URL"] %>
  census_auth_token: <%= ENV["CENSUS_AUTH_TOKEN"] %>
  sms:
    service_url: <%= ENV["SMS_SERVICE_URL"] %>
    username: <%= ENV["SMS_USERNAME"] %>
    password: <%= ENV["SMS_PASSWORD"] %>
    service_id: "<%= ENV['SMS_SERVICE_ID'] %>"

development:
  <<: *default
  secret_key_base: ff17b08cf4407cc501e53e7d3cafa670df024d636ebf6f875704d5113541b6b7d516bc944c3e0d580849123c67115b3d5f4048a8a71b5b41e1569392d7a489d0
  omniauth:
    developer:
      enabled: true
  geocoder:
    here_api_key: 'fakekey'

test:
  <<: *default
  secret_key_base: 01ec40d7f667d5be378f89c93f45ccbc0929ba16ad0622d03d1ab7bb6f5f6d0e1344dd72b7bfb65b1282cdede98a18ca1bdcd3c68cbb1d113bbedc87bba520bf
  census_url: census.url
  census_auth_token: secret
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true
  geocoder:
    here_api_key: 'fakekey'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid: <%= !ENV["SENDGRID_USERNAME"].blank? %>
  smtp_username: <%= ENV["SMTP_USERNAME"] || ENV["SENDGRID_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] || ENV["SENDGRID_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] || "smtp.sendgrid.net" %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] || "heroku.com" %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
  sentry_enabled: true
