# frozen_string_literal: true

source "https://rubygems.org"

# Declare your gem's dependencies in decidim-file_authorization_handler.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

DECIDIM_VERSION = { git: "https://github.com/CodiTramuntana/decidim", branch: "release/0.27-stable" }

group :development, :test do
  gem "bootsnap", require: false
  gem "decidim", DECIDIM_VERSION
  gem "decidim-cdtb", path: "/home/oliver/prog/decidim/modules/decidim-cdtb"
  gem "letter_opener_web"
  gem "listen"
end

group :development do
  gem "rubocop", "~> 1.28.0"
end
